---
- name: Automatic Remediation of a server
  hosts: Test-RHEL-7.9-1
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  
  rules:
    - name: CPU full on server
      condition: event.alert.labels.job == "hostCpuUsageAlert" or event.alert.status == "firing"
      action:
        run_job_template:
          #           name: 100_EDA_01_cpu_usage_alert
          name: 100_EDA_01_cpu_usage_alert_Self-healing
          organization: Venetian
            #  job_args:
            #limit: "{{ event.meta.hosts }}"
        # run_playbook:
        #  name: cpu-playbook.yml
