---
- name: Automatic Remediation of a server
  hosts: rhel7
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  
  rules:
    - name: CPU full on server
      condition: event.alert.labels.job == "hostCpuUsageAlert" or event.alert.status == "firing"
      action:
        run_playbook:
          name: cpu-playbook.yml
