---
- name: Listen for events on a webhook
  hosts: rhel7
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  
  rules:
  - name: Say Warning
    condition: event.payload.message == "Call Trace"
    action:
      run_playbook:
        name: warning.yml

